"""fix title same problem

Revision ID: 1f6f103026a7
Revises: bbb986ef5110
Create Date: 2016-07-19 09:52:58.299231

"""

# revision identifiers, used by Alembic.
revision = '1f6f103026a7'
down_revision = 'bbb986ef5110'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='posts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'posts', ['title'], unique=True)
    ### end Alembic commands ###
