"""add like

Revision ID: 79e8ddb5acdb
Revises: 8f573a02d821
Create Date: 2016-08-02 22:27:07.691687

"""

# revision identifiers, used by Alembic.
revision = '79e8ddb5acdb'
down_revision = '8f573a02d821'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_like_timestamp'), 'like', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_like_timestamp'), table_name='like')
    op.drop_table('like')
    ### end Alembic commands ###
