"""add articles' title

Revision ID: bbb986ef5110
Revises: None
Create Date: 2016-07-17 19:17:27.800985

"""

# revision identifiers, used by Alembic.
revision = 'bbb986ef5110'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.Unicode(length=128), nullable=True))
    op.create_unique_constraint(None, 'posts', ['title'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
